using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace fsEco.PublicData.JobGeneration.JobTypes.CargoTransport
{
    public class CargoTypes
    {
        public static readonly string[] Types = new string[]
        {
            "Electronics",
            "Textiles",
            "Office Supplies",
            "Home Appliances",
            "Furniture",
            "Clothing",
            "Books",
            "Toys",
            "Paper Rolls",
            "Kitchenware",
            "Machinery Parts",
            "Steel Beams",
            "Construction Equipment",
            "Hydraulic Components",
            "Cement Bags",
            "Pipes and Tubing",
            "Generators",
            "Drilling Equipment",
            "Safety Gear",
            "Industrial Tools",
            "Wheat",
            "Corn",
            "Cotton",
            "Fertilizer",
            "Tractor Parts",
            "Hay Bales",
            "Seeds",
            "Pesticides",
            "Coffee Beans",
            "Raw Sugar",
            "Fresh Produce",
            "Frozen Meat",
            "Dairy Products",
            "Bottled Water",
            "Canned Food",
            "Seafood (Chilled)",
            "Bakery Goods",
            "Chocolate",
            "Ice Cream",
            "Wine & Spirits",
            "Medical Supplies",
            "Blood Packs",
            "Oxygen Tanks",
            "PPE Kits",
            "Vaccines",
            "Antibiotics",
            "Emergency Rations",
            "Defibrillators",
            "Quarantine Equipment",
            "Wheelchairs",
            "Lithium Batteries",
            "Solar Panels",
            "Server Racks",
            "Power Cables",
            "Fuel Cells",
            "Charging Stations",
            "Drone Parts",
            "Communication Equipment",
            "Electric Motors",
            "Telecom Antennas",
            "Artwork",
            "Musical Instruments",
            "Fragile Glassware",
            "Fine Ceramics",
            "Vintage Antiques",
            "Scientific Instruments",
            "Live Fish",
            "Aquarium Tanks",
            "Rare Books",
            "Exhibition Equipment",
            "Fireworks",
            "Ammunition",
            "Paint Thinner",
            "Radioactive Material",
            "Flammable Liquids",
            "Gas Cylinders",
            "Corrosive Chemicals",
            "Biohazard Waste",
            "Fire Suppressants",
            "Mercury Thermometers",
            "Motorcycle Crates",
            "Car Engines",
            "Spare Tires",
            "Windshields",
            "EV Batteries",
            "Car Seats",
            "Alloy Wheels",
            "Brake Systems",
            "Vehicle Control Units",
            "ATV Parts",
            "Currency Shipments",
            "Voting Machines",
            "Film Equipment",
            "Sports Gear",
            "Satellite Components",
            "Board Game Crates",
            "Cosplay Costumes",
            "Comic Book Collections",
            "Animal Feed",
            "Weather Balloons",
            "Mystery Cargo",
            "AI Drone Kits",
            "Prototype Devices",
            "eSports Hardware",
            "Theater Set Pieces"
        };
    }
}
